// lib/data.ts
import { Project } from "./dataTypes";

export const projectsData: Project[] = [
  {
    id : "0",
    type: "3D",
    title: "Antar Dimensi",
    company: "Personal Project",
    desc: "Andai kita bisa berkomunikasi dengan dimensi lain, apa yang akan kita katakan? hanya ruang yang mengeksplorasi komunikasi dan emosi.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEak6v5i9eSOlL7yNsFi8JwX4rtQRbuIfEPhmD",
    videoUrl: null,
    techStack: [
      { name: "Blender", url: "/icons/blender.png" },
    ],
    linkUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEak6v5i9eSOlL7yNsFi8JwX4rtQRbuIfEPhmD",
  },
  {
    id : "1",
    type: "3D",
    title: "Bank Jembut",
    company: "Personal Project",
    desc: "Bank ini adalah bank yang melayani semua kebutuhan finansial Anda dengan sentuhan humor dan keunikan.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5ME5YVCoOlfSM8OdFWzYR9eZcAjUQKu5CHht7wn",
    videoUrl: null,
    techStack: [
      { name: "Blender", url: "/icons/blender.png" },
    ],
    linkUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5ME5YVCoOlfSM8OdFWzYR9eZcAjUQKu5CHht7wn",
  },
  {
    id : "2",
    type: "3D",
    title: "Cyberpunk",
    company: "Personal Project",
    desc: "Lowpoly ini representasi sepinya hidup dan kehampaan",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEwpmZpCORnhzPFs2dYXxDo0JZuTW65i8crQKA",
    videoUrl: null,
    techStack: [
      { name: "Blender", url: "/icons/blender.png" },
    ],
    linkUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEwpmZpCORnhzPFs2dYXxDo0JZuTW65i8crQKA",
  },
  {
    id : "3",
    type: "3D",
    title: "Fiksi",
    company: "Personal Project",
    desc: "Hutan kesepian, kala sinar merekah",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEEPCBNm7WsbVvtF60NLHkYacUJx1wgo2XZ98m",
    videoUrl: null,
    techStack: [
      { name: "Blender", url: "/icons/blender.png" },
    ],
    linkUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEEPCBNm7WsbVvtF60NLHkYacUJx1wgo2XZ98m",
  },
  {
    id : "4",
    type: "3D",
    title: "Lintas Dimensi",
    company: "Personal Project",
    desc: "Perjalanan melintasi dimensi, menembus batas realitas.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEX7D48iFTDoU8KQLVC2wgBkjZuyt3flG0X1iW",
    videoUrl: null,
    techStack: [
      { name: "Blender", url: "/icons/blender.png" },
    ],
    linkUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEX7D48iFTDoU8KQLVC2wgBkjZuyt3flG0X1iW",
  },
  {
    id : "5",
    type: "3D",
    title: "Rolercoaster",
    company: "Personal Project",
    desc: "Atas bawah ku terus menempel hingga lupa daratan",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEP0sVrY5D3xrLB2oWHtngRCjFbAVT5iaspIKy",
    videoUrl: null,
    techStack: [
      { name: "Blender", url: "/icons/blender.png" },
    ],
    linkUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEP0sVrY5D3xrLB2oWHtngRCjFbAVT5iaspIKy",
  },
  {
    id : "6",
    type: "Design",
    title: "Biro Desain Komunikasi Visual",
    company: "EM UB 2022",
    desc: "EM UB 2022 adalah sebuah organisasi tingkat mahasiswa yang memiliki daya juang tinggi memberikan pelayan lebih kepada mahasiswa di tingkat universitas dan juga memberikan pengalaman lebih kepada mahasiswa se-universitas Brawijaya.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5ME3GaF6VJxkHgmdGue6K0yIEvF4c1Lth79qYia",
    videoUrl: null,
    techStack: [
      { name: "Adobe Premiere Pro", url: "/icons/adobe-premierepro.png" },
      { name: "Adobe After Effects", url: "/icons/adobe-aftereffects.png" },
      { name: "Adobe Photoshop", url: "/icons/adobe-photoshop.png" },
    ],
    linkUrl: "https://www.instagram.com/em_ubofficial?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id : "7",
    type: "Design",
    title: "Kementrian Komunikasi dan Informatika",
    company: "EM UB 2023",
    desc: "EM UB 2023 adalah organisasi mahasiswa tingkat universitas yang menjunjung tinggi nilai kepemimpinan dan pertumbuhan, sehingga EM UB 2023 bertujuan untuk mengasah pola pikir mahasiswa agar mampu berpikir kritis, kreatif, dan produktif di tengah kesibukan perkuliahan.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5ME0YpaxImO10M7D2iUrul4HdmExBLKFeWfJSng",
    videoUrl: null,
    techStack: [
      { name: "Adobe Premiere Pro", url: "/icons/adobe-premierepro.png" },
      { name: "Adobe After Effects", url: "/icons/adobe-aftereffects.png" },
      { name: "Adobe Photoshop", url: "/icons/adobe-photoshop.png" },
      { name: "Figma", url: "/icons/figma.png" },
    ],
    linkUrl: "https://www.instagram.com/em_ubofficial?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id : "8",
    type: "Design",
    title: "Graphic Design",
    company: "Google Developer Student Clubs UB 2023",
    desc: "GDSC UB 2023 adalah sebuah komunitas yang berfungsi sebagai platform connection bagi mahasiswa dari berbagai latar belakang dan jurusan yang memiliki ketertarikan pada teknologi. Belajar bersama dengan orang-orang yang memiliki passion serupa membuat pengalaman di GDSC UB 2023 menjadi lebih menarik dan menyenangkan.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEMjhMfKhcJgWqnwUDEmPkaQ0AB3Vl7OTKiLSX",
    videoUrl: null,
    techStack: [
      { name: "Adobe Premiere Pro", url: "/icons/adobe-premierepro.png" },
      { name: "Adobe After Effects", url: "/icons/adobe-aftereffects.png" },
      { name: "Figma", url: "/icons/figma.png" },
    ],
    linkUrl: "https://www.instagram.com/p/Cxkn-k3rzqf/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
  },
  {
    id : "9",
    type: "Design",
    title: "Lead of Media Creative",
    company: "Google Developer Group on Campus UB 2024",
    desc: "GDGOC 2024 adalah komunitas mahasiswa lintas jurusan yang berfokus pada pengembangan minat serta keterampilan di bidang teknologi. Melalui berbagai kegiatan, diskusi, dan kolaborasi, GDGOC 2024 menjadi wadah bagi mahasiswa untuk bertukar ide, mengasah kemampuan, serta membangun relasi. Suasana belajar bersama pun terasa lebih seru dan bermakna karena didukung semangat kebersamaan serta inspirasi dari setiap anggota.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEVV13xYP8FCdSg3um9IJToBDHwZ0NbLiU2XaY",
    videoUrl: null,
    techStack: [
      { name: "Adobe Premiere Pro", url: "/icons/adobe-premierepro.png" },
      { name: "Adobe After Effects", url: "/icons/adobe-aftereffects.png" },
      { name: "Figma", url: "/icons/figma.png" },
    ],
    linkUrl: "https://www.instagram.com/p/DBXvSjySXXU/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
  },
  {
    id : "10",
    type: "Design",
    title: "Graphic Design",
    company: "Google I/O Extended Jakarta 2024",
    desc: "Google I/O Extended Jakarta adalah acara komunitas yang diadakan secara lokal oleh GDG, GDSC, maupun komunitas teknologi lainnya untuk menghadirkan pengalaman konferensi utama Google I/O lebih dekat ke peserta. Lewat rangkaian kegiatan seperti watch party, tech talk, workshop, hingga networking, peserta tidak hanya mendapatkan wawasan terbaru seputar teknologi, tetapi juga berkesempatan mengasah keterampilan secara langsung. Dengan semangat inovasi Google I/O, acara ini menjadi wadah belajar, berjejaring, dan saling menginspirasi bagi para penggiat teknologi di tingkat lokal.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5ME6sQaC3zGRdGVCAXBDFwUa3t1YcberPhkvqOn",
    videoUrl: null,
    techStack: [
      { name: "Figma", url: "/icons/figma.png" },
    ],
    linkUrl: "https://www.instagram.com/p/C8y-1cQSVmo/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
  },
  {
    id : "11",
    type: "Design",
    title: "Graphic Design",
    company: "Mahakarya Brawijaya 2022",
    desc: "Mahakarya Brawijaya adalah sebuah kegiatan konser yang diselenggarakan oleh divisi BUDPORA EM UB 2022, menampilkan berbagai talenta dari Brawijaya serta menghadirkan sejumlah penyanyi terkenal seperti Wake Up Iris, Lomba Sihir, IDGITAF, The Overtunes, dan Yovie & Nuno.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MExdbRvb8hRWg8Dz5Xdb7VwxEjJUvSmPatCLI3",
    videoUrl: null,
    techStack: [
      { name: "Corel Draw", url: "/icons/corel-draw.png" },
    ],
    linkUrl: "https://www.instagram.com/mahakaryabrawijaya?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  },
  {
    id : "11",
    type: "Mobile",
    title: "Bookish",
    company: "College Project",
    desc: "Bookish adalah aplikasi berbasis kotlin yang mengintegrasikan firebase, cloudinary, google books API, dan google sign-in untuk menyediakan platform bagi pengguna dalam menjelajahi, menyimpan, dan berbagi rekomendasi buku secara efisien.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEP8jwn35D3xrLB2oWHtngRCjFbAVT5iaspIKy",
    videoUrl: null,
    techStack: [
      { name: "Kotlin", url: "/icons/kotlin.png" },
      { name: "Cloudinary", url: "/icons/cloudinary.png" },
      { name: "Firebase", url: "/icons/firebase.png" },
    ],
    linkUrl: "https://github.com/hnifnurh/Bookish",
  },
  {
    id : "12",
    type: "Mobile",
    title: "Voice Memos",
    company: "Code ghostwriter",
    desc: "Voice Memos adalah aplikasi berbasis fluter yang berfungsi sebagai perekam suara.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEhppNl8Z4KJagULNtvTVS8AXP9Wk1xm3FiBcu",
    videoUrl: null,
    techStack: [
      { name: "Flutter", url: "/icons/flutter.png" },
      { name: "Dart", url: "/icons/dart.png" },
    ],
    linkUrl: "https://github.com/hnifnurh/voice-memo.git",
  },
  {
    id : "13",
    type: "UI/UX",
    title: "Kampung Budaya 2023",
    company: "BUDPORA EM UB 2023",
    desc: "Kampung Budaya adalah acara tahunan yang diselenggarakan oleh BUDPORA EM UB 2023 sebagai bentuk apresiasi terhadap keberagaman budaya Indonesia. Acara ini menampilkan berbagai pertunjukan seni, pameran budaya, dan kegiatan interaktif yang mengajak peserta untuk lebih mengenal dan menghargai warisan budaya nusantara.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEw1ULAbORnhzPFs2dYXxDo0JZuTW65i8crQKA", 
    videoUrl: null,
    techStack: [
      { name: "Premiere Pro", url: "/icons/pr.svg" },
      { name: "After Effects", url: "/icons/ae.svg" },
    ],
    linkUrl:
      "https://kampung-budaya.vercel.app/",
  },
  {
    id : "13",
    type: "UI/UX",
    title: "Raja Brawijaya 2023",
    company: "EM UB 2023",
    desc: "Raja Brawijaya adalah rangkaian pertama mahasiswa baru Universitas Brawiaya yang bertujuan untuk memperkenalkan budaya, tradisi, dan nilai-nilai luhur Universitas Brawijaya kepada mahasiswa baru.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5MEkOFbYPq7BXD8kaJIWLHu591ivjbYU3A6Kd0N", 
    videoUrl: null,
    techStack: [
      { name: "Premiere Pro", url: "/icons/pr.svg" },
      { name: "After Effects", url: "/icons/ae.svg" },
    ],
    linkUrl:
      "https://rajabrawijaya.ub.ac.id/",
  },
  {
    id : "14",
    type: "UI/UX",
    title: "Masyarakat Iktiologi Indonesia",
    company: "Project for Client",
    desc: "Masyarakat Iktiologi Indonesia (MII) atau Indonesian Ichthyological Society (IIS) adalah organisasi profesional nirlaba yang menaungi individu yang memiliki perhatian pada ikan (Pisces), termasuk peneliti, dosen, mahasiswa, LSM, pengusaha, hingga pemerhati ikan. Organisasi ini didirikan pada 6 Juni 2000 di Bogor, disahkan melalui Akta Notaris No. 01 tanggal 1 Desember 2014, dan resmi diakui berdasarkan SK Menteri Hukum dan HAM No. AHU-0000019.AH.01.Tahun 2015 tanggal 6 Januari 2015. Logo MII menampilkan ikan coelacanth (Latimeria menadoensis), yang dijuluki fosil hidup karena keberadaannya di bumi sudah ada sejak 400 juta tahun lalu, jauh sebelum dinosaurus.",
    imageUrl: "https://a26kr599dm.ufs.sh/f/lqDWJCaxK5ME74Y9FSC8A2dB6LXSFaQ3RtCWNv4rEOsy9KZw", 
    videoUrl: null,
    techStack: [
      { name: "Premiere Pro", url: "/icons/pr.svg" },
      { name: "After Effects", url: "/icons/ae.svg" },
    ],
    linkUrl:
      "https://iktiologi-indonesia.or.id/home",
  },
  {
    id : "15",
    type: "Videography",
    title: "Impersepsi",
    company: "Short Movie Competition 2021",
    desc: "Masyarakat Iktiologi Indonesia (MII) atau Indonesian Ichthyological Society (IIS) adalah organisasi profesional nirlaba yang menaungi individu yang memiliki perhatian pada ikan (Pisces), termasuk peneliti, dosen, mahasiswa, LSM, pengusaha, hingga pemerhati ikan. Organisasi ini didirikan pada 6 Juni 2000 di Bogor, disahkan melalui Akta Notaris No. 01 tanggal 1 Desember 2014, dan resmi diakui berdasarkan SK Menteri Hukum dan HAM No. AHU-0000019.AH.01.Tahun 2015 tanggal 6 Januari 2015. Logo MII menampilkan ikan coelacanth (Latimeria menadoensis), yang dijuluki fosil hidup karena keberadaannya di bumi sudah ada sejak 400 juta tahun lalu, jauh sebelum dinosaurus.",
    imageUrl: "/images/impersepsi.png", 
    videoUrl: "https://www.youtube.com/embed/LVvpWqG3vbM?si=2Th3PLJZ-hCjsfAc",
    techStack: [
      { name: "Premiere Pro", url: "/icons/pr.svg" },
    ],
    linkUrl:
      "https://youtu.be/LVvpWqG3vbM",
  },
  {
    id : "15",
    type: "Videography",
    title: "Impersepsi",
    company: "Short Movie Competition 2021",
    desc: "Masyarakat Iktiologi Indonesia (MII) atau Indonesian Ichthyological Society (IIS) adalah organisasi profesional nirlaba yang menaungi individu yang memiliki perhatian pada ikan (Pisces), termasuk peneliti, dosen, mahasiswa, LSM, pengusaha, hingga pemerhati ikan. Organisasi ini didirikan pada 6 Juni 2000 di Bogor, disahkan melalui Akta Notaris No. 01 tanggal 1 Desember 2014, dan resmi diakui berdasarkan SK Menteri Hukum dan HAM No. AHU-0000019.AH.01.Tahun 2015 tanggal 6 Januari 2015. Logo MII menampilkan ikan coelacanth (Latimeria menadoensis), yang dijuluki fosil hidup karena keberadaannya di bumi sudah ada sejak 400 juta tahun lalu, jauh sebelum dinosaurus.",
    imageUrl: "/images/impersepsi.png", 
    videoUrl: "https://www.youtube.com/embed/LVvpWqG3vbM?si=2Th3PLJZ-hCjsfAc",
    techStack: [
      { name: "Premiere Pro", url: "/icons/pr.svg" },
      { name: "After Effects", url: "/icons/ae.svg" },
    ],
    linkUrl:
      "https://iktiologi-indonesia.or.id/home",
  },
  
];

