// lib/data.ts
import { Project } from "./dataTypes";

export const projectsData: Project[] = [
  {
    id : "1",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "2",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "3",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "4",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "5",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "6",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "7",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "8",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/hanif.webp",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "9",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/hanif.webp",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "10",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/hanif.webp",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "11",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "12",
    type: "Website",
    title: "Bookish",
    company: "College Project",
    desc: "Official website for TEDx University of Brawijaya, showcasing speakers and event information for the 2025 conference.",
    imageUrl: "/images/bookish.png",
    videoUrl: null,
    techStack: [
      { name: "Next.js", url: "/icons/nextjs.svg" },
      { name: "TailwindCSS", url: "/icons/tailwind.svg" },
    ],
    linkUrl: "https://tedxub.com",
  },
  {
    id : "13",
    type: "Videography",
    title: "Memanggil",
    company: "Personal Project",
    desc: "Short film exploring nostalgic communication and emotions.",
    imageUrl: "/images/ted.jpg", 
    videoUrl:
      "https://www.youtube.com/embed/uA0eLmYm9w4?autoplay=1&mute=1&loop=1&playlist=uA0eLmYm9w4",
    techStack: [
      { name: "Premiere Pro", url: "/icons/pr.svg" },
      { name: "After Effects", url: "/icons/ae.svg" },
    ],
    linkUrl:
      "https://www.youtube.com/embed/uA0eLmYm9w4?autoplay=1&mute=1&loop=1&playlist=uA0eLmYm9w4",
  },
  
];

